### PR TITLE
Better HealthKitController

### LINKED ISSUE #51: HealthKitController seems to use lots of force unwrapping
This should be refactored to be safer.

### PR DESCRIPTION
**Pull request by Priva28**
- Replaced current methods to be safer, with completions and more customisability (including units and date (for both health and activity data))
- Removed @ Published activity values
- Added ActivityResult struct for getting activity values in completion
- Re-renamed RingColor to RingType as it is used for more than just color.
- Moved RingType to its own file

### CODE REVIEW

**Comment by Priva28** [comment]
Build fails because dev branch is still using old methods. When competitions-screen is merged, it should work.

**Comment by Priva28** [comment]
dont merge yet

**Comment by Priva28** [comment]
ok all good now I think
- Readded @ Published values
- Added method to update values for today
- Show this in CompetitionView
- Update CompetitionCell to not show activity rings

**Comment by Priva28** [comment]
builds fine for me can someone else check?

**Comment by wfltaylor** [comment]
I'll work on updating the tests to work for the new controller.

**Comment by wfltaylor** [comment]
Tests are fixed for the new controller, but they are legitimately failing. It looks like standGoal and exerciseGoal are incorrect.

**Review by RomanEsin — APPROVED** [review]

**Review by wfltaylor — APPROVED** [review]

**Pull request merged**
