### PR TITLE
Added unit test target and basic range conversion test

### PR DESCRIPTION
**Pull request by wfltaylor**

### CODE REVIEW

**Comment by Priva28** [comment]
Does this just test the convert function? How would it help in the future? I’ve never written tests so I honestly have no idea 😂

**Review by RomanEsin — APPROVED** [review]

**Review by Priva28 — APPROVED** [review]

**Comment by RomanEsin** [comment]
> Does this just test the convert function? How would it help in the future? I’ve never written tests so I honestly have no idea 😂

Other than that we would do networking tests and connection with backend/cloudkit test, so that is important to have tests.

**Comment by Priva28** [comment]
Sounds good 👍

**Comment by wfltaylor** [comment]
> Does this just test the convert function? How would it help in the future? I’ve never written tests so I honestly have no idea 😂

It means if the function is ever changed in a way that somehow breaks it we can find out.

**Pull request merged**
