### PR TITLE
Created a simple NetworkManager for handling URL requests.

### PR DESCRIPTION
**Pull request by RomanEsin**

### CODE REVIEW

**Comment by wfltaylor** [comment]
Maybe move NetworkError into the class?

**Comment by RomanEsin** [comment]
Hmm, I'm not really into nested types thing. I've seen you've put enum below the methods in the class in HKController, so I guess we should stick with that.

**Comment by Priva28** [comment]
Yep. Other than that it looks good. Clean code 👍

**Comment by Priva28** [comment]
Merge?

**Comment by RomanEsin** [comment]
I already merged!

**Pull request merged**
