### PR TITLE
Remove dependency of the color name being the same as the enum case

### PR DESCRIPTION
**Pull request by wfltaylor**

### CODE REVIEW

**Comment by RomanEsin** [comment]
Maybe you could keep it conform to self, so in the `var color` you just return `Color(self.rawValue)`?

**Comment by wfltaylor** [comment]
That relies on the enum case name being the same as the colour name which may not be what we want. If in the future we change the colours to be called 'exerciseRingColor' to make it clearer then that code would break.

**Comment by RomanEsin** [comment]
Then we could just set each skim case equal to the name of the color `case exercise = "exerciseRingColor"`. That basically does the same thing as you do in the switch case, but if you'd want to use the color name anywhere else, you could easily get it's name by calling RingType.exercise.rawValue.

**Comment by RomanEsin** [comment]
That's basically one of the main uses of enums

**Comment by wfltaylor** [comment]
Can I rename `RingType` to `RingColor` to make it clearer that it is referencing the colour? Otherwise the meaning of 'rawValue' is unclear.

**Comment by RomanEsin** [comment]
Yeah, that'd be better

**Pull request merged**
